language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy sabbahy/reverseproxy:v1_0
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed sabbahy/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user sabbahy/udagram-api-user:v1.0
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend sabbahy/udagram-frontend:v7

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sabbahy/reverseproxy:v1_0
  - docker push sabbahy/udagram-api-feed:v1
  - docker push sabbahy/udagram-api-user:v1.0
  - docker push sabbahy/udagram-frontend:v7
